#include "ui/App.h"
#include "ui/MainWindow.h"
#include "ui/Theme.h"

#include <gtk/gtk.h>

// Generated by glib-compile-resources --generate-source from
// resources/logram.gresource.xml. Name comes from the basename ("logram"
// stripped of ".gresource.xml"), suffixed with "_get_resource".
extern "C" GResource* logram_get_resource(void);

namespace {

void OnWindowDestroy(GtkWidget* /*window*/, gpointer user_data) {
    delete static_cast<MainWindow*>(user_data);
}

void EnsureIconsRegistered() {
    static bool done = false;
    if (done) return;
    done = true;
    // The generated source registers via __attribute__((constructor)); this
    // call is idempotent and guards against any future linker-strip of the
    // constructor (e.g. under LTO with --gc-sections).
    g_resources_register(logram_get_resource());

    // GtkApplication adds /<app-id>/icons automatically from its
    // resource_base_path, but only after the icon theme exists for the
    // display. Doing it explicitly avoids races between display creation
    // and the first window's set_icon_name call.
    GtkIconTheme* theme =
        gtk_icon_theme_get_for_display(gdk_display_get_default());
    if (theme) {
        gtk_icon_theme_add_resource_path(theme, "/com/unitybase/Logram/icons");
    }
}

MainWindow* CreateWindow(GtkApplication* app) {
    EnsureIconsRegistered();
    Theme::Apply();
    auto* mw = new MainWindow(app);
    g_signal_connect(mw->Widget(), "destroy", G_CALLBACK(OnWindowDestroy), mw);
    return mw;
}

void OnActivate(GtkApplication* app, gpointer /*user_data*/) {
    MainWindow* mw = CreateWindow(app);
    gtk_window_present(GTK_WINDOW(mw->Widget()));
}

void OnOpen(GApplication* app, GFile** files, gint n_files,
            const gchar* /*hint*/, gpointer /*user_data*/) {
    MainWindow* mw = CreateWindow(GTK_APPLICATION(app));
    gtk_window_present(GTK_WINDOW(mw->Widget()));
    if (n_files > 0 && files[0]) {
        char* path = g_file_get_path(files[0]);
        if (path) {
            mw->LoadFile(path);
            g_free(path);
        }
    }
}

} // namespace

int App::Run(int argc, char** argv) {
    GtkApplication* app = gtk_application_new(
        "com.unitybase.Logram",
        static_cast<GApplicationFlags>(G_APPLICATION_DEFAULT_FLAGS |
                                       G_APPLICATION_HANDLES_OPEN));
    g_signal_connect(app, "activate", G_CALLBACK(OnActivate), nullptr);
    g_signal_connect(app, "open",     G_CALLBACK(OnOpen),     nullptr);
    const int status = g_application_run(G_APPLICATION(app), argc, argv);
    g_object_unref(app);
    return status;
}